import type { Metadata } from "next";
import "./globals.css";
import TopNavbar from "@/app/components/navbar/TopNavbar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TopNavbar />
        <main>{children}</main>
      </body>
    </html>
  )
}
